### ISSUE TITLE
작동 원리

### ISSUE THREAD

**Issue by mincomk** [blluv/mTransKey#2]
작동 원리가 무엇인가요? 어떻게 뜯었는지 알수 있을까요?

[디코](https://discord.com/users/590826711147347973)

**Comment by blluv** [comment]
작동 원리는 브라우저에서 작동하는 tk 작동 방식을 파이썬으로 구현한거고
transkey 코드 보면서 구현했죠

**Comment by mincomk** [comment]
어떤 코드를 봐야 할수 있나요?
